config/routes.rb
Shipping::Application.routes.draw do
  
  resources :vessels

  resources :staffs

  resources :statuses

  resources :locations

  resources :agents
  
  get "welcome/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "admin/dashboard#index"

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agent.rb
class Agent < ActiveRecord::Base
   validates :name, presence: true,
                    length: { minimum: 6 }
   has_many :ships
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :ships
end

app/models/ship.rb
class Ship < ActiveRecord::Base
  belongs_to :location
  belongs_to :agent
  belongs_to :status
  belongs_to :staff
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :ships
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :ships
end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

  def index
    @agents = Agent.all
  end

  def show
    @agent = Agent.find(params[:id])
  end

  def new
    @agent = Agent.new
  end

  def create
    @agent = Agent.new(agent_params)
    if @agent.save
      redirect_to @agent
    else
      render 'new'
    end
  end
  
  def edit
    @agent = Agent.find(params[:id])
  end
  
  def update
    @agent = Agent.find(params[:id])
 
    if @agent.update_attributes(params.require[:agent].permit(:name, :contact, :location, :phone, :email, :comments))
      redirect_to @agent
    else
      render 'edit'
    end
  end  
    
  private
    def agent_params
      params.require(:agent).permit(:name, :location, :contact, :phone, :email, :comments)
    end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #before_filter do
  #  resource = controller_name.singularize.to_sym
  #  method = "#{resource}_params"
  #  params[resource] &&= send(method) if respond_to?(method, true)
  #end
  
end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base
end

app/controllers/staffs_controller.rb
class StaffsController < InheritedResources::Base
end

app/controllers/statuses_controller.rb
class StatusesController < InheritedResources::Base
end

app/controllers/vessels_controller.rb
class VesselsController < InheritedResources::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agents/edit.html.erb
<h2>Edit this Agent...</h2>
<%= form_for :agent, url: agent_path(@agent.id), method: :patch  do |f| %>
  <% if @agent.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@agent.errors.count, "error") %> prevented 
    	this agent from being saved:</h2>
	<ul>
    <% @agent.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  
  <p>
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </p>
 
  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<h1>Listing Agents</h1>
<%= link_to 'Add a new Agent', new_agent_path %> 
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Contact</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Comments</th>
    <th></th>
    <th></th>
  </tr>
 
  <% @agents.each do |agent| %>
    <tr>
      <td><%= agent.name %></td>
      <td><%= agent.location %></td>
      <td><%= agent.contact %></td>
      <td><%= agent.phone %></td>
      <td><%= agent.email %></td>
      <td><%= agent.comments %></td>
      <td><%= link_to 'Show', agent %></td>
      <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
    </tr>
  <% end %>
</table>

app/views/agents/new.html.erb
<%= form_for :agent, url: agents_path do |f| %>
  <% if @agent.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@agent.errors.count, "error") %> prevented 
    	this agent from being saved:</h2>
	<ul>
    <% @agent.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  
  <p>
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </p>
 
  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @agent.name %>
</p>
<p>
  <strong>Location:</strong>
  <%= @agent.location %>
</p>
<p>
  <strong>Contact:</strong>
  <%= @agent.contact %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @agent.phone %>
</p>
<p>
  <strong>Email:</strong>
  <%= @agent.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @agent.comments %>
</p>

<%= link_to 'Back', agents_path %>

app/views/agents/test.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :initials %><br>
    <%= f.text_field :initials %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>Listing staffs</h1>

<table>
  <thead>
    <tr>
      <th>Initials</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.initials %></td>
        <td><%= staff.name %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Initials:</strong>
  <%= @staff.initials %>
</p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/vessels/_form.html.erb
<%= form_for(@vessel) do |f| %>
  <% if @vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% @vessel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lloyds %><br>
    <%= f.text_field :lloyds %>
  </div>
  <div class="field">
    <%= f.label :inmc %><br>
    <%= f.text_field :inmc %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :extra %><br>
    <%= f.text_field :extra %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vessels/edit.html.erb
<h1>Editing vessel</h1>

<%= render 'form' %>

<%= link_to 'Show', @vessel %> |
<%= link_to 'Back', vessels_path %>

app/views/vessels/index.html.erb
<h1>Listing vessels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lloyds</th>
      <th>Inmc</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>Email</th>
      <th>Extra</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.name %></td>
        <td><%= vessel.lloyds %></td>
        <td><%= vessel.inmc %></td>
        <td><%= vessel.phone %></td>
        <td><%= vessel.fax %></td>
        <td><%= vessel.email %></td>
        <td><%= vessel.extra %></td>
        <td><%= link_to 'Show', vessel %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

app/views/vessels/new.html.erb
<h1>New vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', vessels_path %>

app/views/vessels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vessel.name %>
</p>

<p>
  <strong>Lloyds:</strong>
  <%= @vessel.lloyds %>
</p>

<p>
  <strong>Inmc:</strong>
  <%= @vessel.inmc %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vessel.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @vessel.fax %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vessel.email %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @vessel.extra %>
</p>

<%= link_to 'Edit', edit_vessel_path(@vessel) %> |
<%= link_to 'Back', vessels_path %>

app/views/welcome/index.html.erb
<h1>Welcome Rails!</h1>
<%= link_to "Agents", controller: "agents" %>